node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            try {
                sh 'mvn test'
            } finally {
                junit 'target/surefire-reports/*.xml'
            }
        }
        stage('Manual Approval') {
            def value = input message: 'Lanjutkan ke tahap Deploy?',
                parameters: [choice(name: 'Validasi', choices: ['Proceed', 'Abort'], description: 'klik Proceed untuk melanjutkan eksekusi pipeline ke tahap Deploy atau Abort untuk menghentikan eksekusi pipeline')]
            if (value == 'Abort') {
                currentBuild.result = 'ABORTED'
                error('Pipeline Aborted.')
            }
        }
        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
        }
    }
}